//
// File generated by script 'C:\Users\benjo\Documents\repos\C++\audio_controller\ext\generate_tone_data.js' on 08/13/2026 at 00:37.
// Contains samples of sine waves for all notes (1 periods minimum), octaves 3-7, mapped from [0, 1] => [0, 255], at a sample rate of ~4.10 KHz.
//

#ifndef AUDIO_CONTROLLER_MUSICAL_NOTE_DATA_H
#define AUDIO_CONTROLLER_MUSICAL_NOTE_DATA_H
#include <cmath>

#include "sine_table.h"
#include "musical_note.h"

namespace musical_note_data {
    namespace data {   
        //Note names
        constexpr auto MUSICAL_NOTE_NAME_NONE = "";
        
        constexpr auto MUSICAL_NOTE_NAME_C = "C";
		constexpr auto MUSICAL_NOTE_NAME_C_Sharp = "C#";
		constexpr auto MUSICAL_NOTE_NAME_D_Flat = "Db";
		constexpr auto MUSICAL_NOTE_NAME_D = "D";
		constexpr auto MUSICAL_NOTE_NAME_D_Sharp = "D#";
		constexpr auto MUSICAL_NOTE_NAME_E_Flat = "Eb";
		constexpr auto MUSICAL_NOTE_NAME_E = "E";
		constexpr auto MUSICAL_NOTE_NAME_F = "F";
		constexpr auto MUSICAL_NOTE_NAME_F_Sharp = "F#";
		constexpr auto MUSICAL_NOTE_NAME_G_Flat = "Gb";
		constexpr auto MUSICAL_NOTE_NAME_G = "G";
		constexpr auto MUSICAL_NOTE_NAME_G_Sharp = "G#";
		constexpr auto MUSICAL_NOTE_NAME_A_Flat = "Ab";
		constexpr auto MUSICAL_NOTE_NAME_A = "A";
		constexpr auto MUSICAL_NOTE_NAME_A_Sharp = "A#";
		constexpr auto MUSICAL_NOTE_NAME_B_Flat = "Bb";
		constexpr auto MUSICAL_NOTE_NAME_B = "B";
        
        //Note names, octave 3
		constexpr auto MUSICAL_NOTE_NAME_C_OCTAVE_3 = "C3";
		constexpr auto MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_3 = "C#3";
		constexpr auto MUSICAL_NOTE_NAME_D_Flat_OCTAVE_3 = "Db3";
		constexpr auto MUSICAL_NOTE_NAME_D_OCTAVE_3 = "D3";
		constexpr auto MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_3 = "D#3";
		constexpr auto MUSICAL_NOTE_NAME_E_Flat_OCTAVE_3 = "Eb3";
		constexpr auto MUSICAL_NOTE_NAME_E_OCTAVE_3 = "E3";
		constexpr auto MUSICAL_NOTE_NAME_F_OCTAVE_3 = "F3";
		constexpr auto MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_3 = "F#3";
		constexpr auto MUSICAL_NOTE_NAME_G_Flat_OCTAVE_3 = "Gb3";
		constexpr auto MUSICAL_NOTE_NAME_G_OCTAVE_3 = "G3";
		constexpr auto MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_3 = "G#3";
		constexpr auto MUSICAL_NOTE_NAME_A_Flat_OCTAVE_3 = "Ab3";
		constexpr auto MUSICAL_NOTE_NAME_A_OCTAVE_3 = "A3";
		constexpr auto MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_3 = "A#3";
		constexpr auto MUSICAL_NOTE_NAME_B_Flat_OCTAVE_3 = "Bb3";
		constexpr auto MUSICAL_NOTE_NAME_B_OCTAVE_3 = "B3";
		
		//Note names, octave 4
		constexpr auto MUSICAL_NOTE_NAME_C_OCTAVE_4 = "C4";
		constexpr auto MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_4 = "C#4";
		constexpr auto MUSICAL_NOTE_NAME_D_Flat_OCTAVE_4 = "Db4";
		constexpr auto MUSICAL_NOTE_NAME_D_OCTAVE_4 = "D4";
		constexpr auto MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_4 = "D#4";
		constexpr auto MUSICAL_NOTE_NAME_E_Flat_OCTAVE_4 = "Eb4";
		constexpr auto MUSICAL_NOTE_NAME_E_OCTAVE_4 = "E4";
		constexpr auto MUSICAL_NOTE_NAME_F_OCTAVE_4 = "F4";
		constexpr auto MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_4 = "F#4";
		constexpr auto MUSICAL_NOTE_NAME_G_Flat_OCTAVE_4 = "Gb4";
		constexpr auto MUSICAL_NOTE_NAME_G_OCTAVE_4 = "G4";
		constexpr auto MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_4 = "G#4";
		constexpr auto MUSICAL_NOTE_NAME_A_Flat_OCTAVE_4 = "Ab4";
		constexpr auto MUSICAL_NOTE_NAME_A_OCTAVE_4 = "A4";
		constexpr auto MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_4 = "A#4";
		constexpr auto MUSICAL_NOTE_NAME_B_Flat_OCTAVE_4 = "Bb4";
		constexpr auto MUSICAL_NOTE_NAME_B_OCTAVE_4 = "B4";
		
		//Note names, octave 5
		constexpr auto MUSICAL_NOTE_NAME_C_OCTAVE_5 = "C5";
		constexpr auto MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_5 = "C#5";
		constexpr auto MUSICAL_NOTE_NAME_D_Flat_OCTAVE_5 = "Db5";
		constexpr auto MUSICAL_NOTE_NAME_D_OCTAVE_5 = "D5";
		constexpr auto MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_5 = "D#5";
		constexpr auto MUSICAL_NOTE_NAME_E_Flat_OCTAVE_5 = "Eb5";
		constexpr auto MUSICAL_NOTE_NAME_E_OCTAVE_5 = "E5";
		constexpr auto MUSICAL_NOTE_NAME_F_OCTAVE_5 = "F5";
		constexpr auto MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_5 = "F#5";
		constexpr auto MUSICAL_NOTE_NAME_G_Flat_OCTAVE_5 = "Gb5";
		constexpr auto MUSICAL_NOTE_NAME_G_OCTAVE_5 = "G5";
		constexpr auto MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_5 = "G#5";
		constexpr auto MUSICAL_NOTE_NAME_A_Flat_OCTAVE_5 = "Ab5";
		constexpr auto MUSICAL_NOTE_NAME_A_OCTAVE_5 = "A5";
		constexpr auto MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_5 = "A#5";
		constexpr auto MUSICAL_NOTE_NAME_B_Flat_OCTAVE_5 = "Bb5";
		constexpr auto MUSICAL_NOTE_NAME_B_OCTAVE_5 = "B5";
		
		//Note names, octave 6
		constexpr auto MUSICAL_NOTE_NAME_C_OCTAVE_6 = "C6";
		constexpr auto MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_6 = "C#6";
		constexpr auto MUSICAL_NOTE_NAME_D_Flat_OCTAVE_6 = "Db6";
		constexpr auto MUSICAL_NOTE_NAME_D_OCTAVE_6 = "D6";
		constexpr auto MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_6 = "D#6";
		constexpr auto MUSICAL_NOTE_NAME_E_Flat_OCTAVE_6 = "Eb6";
		constexpr auto MUSICAL_NOTE_NAME_E_OCTAVE_6 = "E6";
		constexpr auto MUSICAL_NOTE_NAME_F_OCTAVE_6 = "F6";
		constexpr auto MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_6 = "F#6";
		constexpr auto MUSICAL_NOTE_NAME_G_Flat_OCTAVE_6 = "Gb6";
		constexpr auto MUSICAL_NOTE_NAME_G_OCTAVE_6 = "G6";
		constexpr auto MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_6 = "G#6";
		constexpr auto MUSICAL_NOTE_NAME_A_Flat_OCTAVE_6 = "Ab6";
		constexpr auto MUSICAL_NOTE_NAME_A_OCTAVE_6 = "A6";
		constexpr auto MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_6 = "A#6";
		constexpr auto MUSICAL_NOTE_NAME_B_Flat_OCTAVE_6 = "Bb6";
		constexpr auto MUSICAL_NOTE_NAME_B_OCTAVE_6 = "B6";
		
		//Note names, octave 7
		constexpr auto MUSICAL_NOTE_NAME_C_OCTAVE_7 = "C7";
		constexpr auto MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_7 = "C#7";
		constexpr auto MUSICAL_NOTE_NAME_D_Flat_OCTAVE_7 = "Db7";
		constexpr auto MUSICAL_NOTE_NAME_D_OCTAVE_7 = "D7";
		constexpr auto MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_7 = "D#7";
		constexpr auto MUSICAL_NOTE_NAME_E_Flat_OCTAVE_7 = "Eb7";
		constexpr auto MUSICAL_NOTE_NAME_E_OCTAVE_7 = "E7";
		constexpr auto MUSICAL_NOTE_NAME_F_OCTAVE_7 = "F7";
		constexpr auto MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_7 = "F#7";
		constexpr auto MUSICAL_NOTE_NAME_G_Flat_OCTAVE_7 = "Gb7";
		constexpr auto MUSICAL_NOTE_NAME_G_OCTAVE_7 = "G7";
		constexpr auto MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_7 = "G#7";
		constexpr auto MUSICAL_NOTE_NAME_A_Flat_OCTAVE_7 = "Ab7";
		constexpr auto MUSICAL_NOTE_NAME_A_OCTAVE_7 = "A7";
		constexpr auto MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_7 = "A#7";
		constexpr auto MUSICAL_NOTE_NAME_B_Flat_OCTAVE_7 = "Bb7";
		constexpr auto MUSICAL_NOTE_NAME_B_OCTAVE_7 = "B7";
    
        /**
         * Sine wave samples for note C, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_C_3[] { 0x80, 0x99, 0xB1, 0xC8, 0xDB, 0xEB, 0xF7, 0xFD, 0xFF, 0xFB, 0xF3, 0xE6, 0xD5, 0xC0, 0xA9, 0x90, 0x77, 0x5E, 0x46, 0x30, 0x1E, 0x10, 0x06, 0x01, 0x01, 0x06, 0x10, 0x1E, 0x31, 0x46, 0x5E, 0x77 };

		/**
         * Sine wave samples for note C, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_C_4[] { 0x80, 0xB1, 0xDB, 0xF7, 0xFF, 0xF3, 0xD5, 0xA9, 0x77, 0x46, 0x1E, 0x06, 0x01, 0x10, 0x31, 0x5E };

		/**
         * Sine wave samples for note C, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_C_5[] { 0x80, 0xDB, 0xFF, 0xD5, 0x77, 0x1E, 0x01, 0x31 };

		/**
         * Sine wave samples for note C, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_C_6[] { 0x80, 0xFF, 0x77, 0x01 };

		/**
         * Sine wave samples for note C, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_C_7[] { 0x80, 0x77 };

		/**
         * Sine wave samples for note C_Sharp, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_C_Sharp_3[] { 0x80, 0x9A, 0xB4, 0xCB, 0xDF, 0xEF, 0xF9, 0xFF, 0xFE, 0xF8, 0xEC, 0xDB, 0xC7, 0xAF, 0x95, 0x7A, 0x5F, 0x46, 0x2F, 0x1C, 0x0D, 0x04, 0x00, 0x02, 0x0A, 0x16, 0x28, 0x3E, 0x56, 0x70 };

		/**
         * Sine wave samples for note C_Sharp, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_C_Sharp_4[] { 0x80, 0xB4, 0xDF, 0xF9, 0xFE, 0xEC, 0xC7, 0x95, 0x5F, 0x2F, 0x0D, 0x00, 0x0A, 0x28, 0x56 };

		/**
         * Sine wave samples for note C_Sharp, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_C_Sharp_5[] { 0x80, 0xDF, 0xFE, 0xC7, 0x5F, 0x0D, 0x0A, 0x56 };

		/**
         * Sine wave samples for note C_Sharp, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_C_Sharp_6[] { 0x80, 0xFE, 0x5F, 0x0A };

		/**
         * Sine wave samples for note C_Sharp, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_C_Sharp_7[] { 0x80, 0x5F };

		/**
         * Sine wave samples for note D, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_D_3[] { 0x80, 0x9C, 0xB7, 0xCF, 0xE3, 0xF3, 0xFC, 0xFF, 0xFC, 0xF2, 0xE3, 0xCE, 0xB6, 0x9B, 0x7E, 0x62, 0x47, 0x2F, 0x1B, 0x0C, 0x03, 0x00, 0x04, 0x0E, 0x1D, 0x32, 0x4B, 0x66 };

		/**
         * Sine wave samples for note D, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_D_4[] { 0x80, 0xB7, 0xE3, 0xFC, 0xFC, 0xE3, 0xB6, 0x7E, 0x47, 0x1B, 0x03, 0x04, 0x1D, 0x4B };

		/**
         * Sine wave samples for note D, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_D_5[] { 0x80, 0xE3, 0xFC, 0xB6, 0x47, 0x03, 0x1D };

		/**
         * Sine wave samples for note D, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_D_6[] { 0x80, 0xFC, 0x47, 0x1D };

		/**
         * Sine wave samples for note D, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_D_7[] { 0x80, 0x47 };

		/**
         * Sine wave samples for note D_Sharp, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_D_Sharp_3[] { 0x80, 0x9E, 0xBA, 0xD3, 0xE8, 0xF6, 0xFE, 0xFE, 0xF8, 0xEA, 0xD7, 0xBF, 0xA3, 0x85, 0x66, 0x49, 0x30, 0x1A, 0x0B, 0x02, 0x00, 0x06, 0x12, 0x24, 0x3C, 0x58, 0x75 };

		/**
         * Sine wave samples for note D_Sharp, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_D_Sharp_4[] { 0x80, 0xBA, 0xE8, 0xFE, 0xF8, 0xD7, 0xA3, 0x66, 0x30, 0x0B, 0x00, 0x12, 0x3C, 0x75 };

		/**
         * Sine wave samples for note D_Sharp, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_D_Sharp_5[] { 0x80, 0xE8, 0xF8, 0xA3, 0x30, 0x00, 0x3C };

		/**
         * Sine wave samples for note D_Sharp, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_D_Sharp_6[] { 0x80, 0xF8, 0x30, 0x3C };

		/**
         * Sine wave samples for note D_Sharp, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_D_Sharp_7[] { 0x80, 0x30 };

		/**
         * Sine wave samples for note E, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_E_3[] { 0x80, 0x9F, 0xBD, 0xD7, 0xEC, 0xF9, 0xFF, 0xFC, 0xF2, 0xE1, 0xC9, 0xAD, 0x8D, 0x6D, 0x4E, 0x32, 0x1B, 0x0B, 0x02, 0x01, 0x07, 0x16, 0x2B, 0x46, 0x64 };

		/**
         * Sine wave samples for note E, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_E_4[] { 0x80, 0xBD, 0xEC, 0xFF, 0xF2, 0xC9, 0x8D, 0x4E, 0x1B, 0x02, 0x07, 0x2B, 0x64 };

		/**
         * Sine wave samples for note E, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_E_5[] { 0x80, 0xEC, 0xF2, 0x8D, 0x1B, 0x07, 0x64 };

		/**
         * Sine wave samples for note E, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_E_6[] { 0x80, 0xF2, 0x1B, 0x64 };

		/**
         * Sine wave samples for note E, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_E_7[] { 0x80, 0x1B };

		/**
         * Sine wave samples for note F, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_F_3[] { 0x80, 0xA1, 0xC1, 0xDB, 0xEF, 0xFC, 0xFF, 0xF9, 0xEB, 0xD5, 0xB8, 0x98, 0x76, 0x55, 0x37, 0x1E, 0x0B, 0x02, 0x01, 0x09, 0x1A, 0x31, 0x4F, 0x70 };

		/**
         * Sine wave samples for note F, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_F_4[] { 0x80, 0xC1, 0xEF, 0xFF, 0xEB, 0xB8, 0x76, 0x37, 0x0B, 0x01, 0x1A, 0x4F };

		/**
         * Sine wave samples for note F, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_F_5[] { 0x80, 0xEF, 0xEB, 0x76, 0x0B, 0x1A };

		/**
         * Sine wave samples for note F, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_F_6[] { 0x80, 0xEB, 0x0B };

		/**
         * Sine wave samples for note F, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_F_7[] { 0x80, 0x0B };

		/**
         * Sine wave samples for note F_Sharp, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_F_Sharp_3[] { 0x80, 0xA3, 0xC4, 0xDF, 0xF3, 0xFE, 0xFE, 0xF4, 0xE1, 0xC6, 0xA6, 0x82, 0x5E, 0x3D, 0x21, 0x0D, 0x02, 0x01, 0x0A, 0x1C, 0x37, 0x57, 0x7A };

		/**
         * Sine wave samples for note F_Sharp, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_F_Sharp_4[] { 0x80, 0xC4, 0xF3, 0xFE, 0xE1, 0xA6, 0x5E, 0x21, 0x02, 0x0A, 0x37, 0x7A };

		/**
         * Sine wave samples for note F_Sharp, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_F_Sharp_5[] { 0x80, 0xF3, 0xE1, 0x5E, 0x02, 0x37 };

		/**
         * Sine wave samples for note F_Sharp, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_F_Sharp_6[] { 0x80, 0xE1, 0x02 };

		/**
         * Sine wave samples for note F_Sharp, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_F_Sharp_7[] { 0x80, 0x02 };

		/**
         * Sine wave samples for note G, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_G_3[] { 0x80, 0xA5, 0xC8, 0xE4, 0xF6, 0xFF, 0xFC, 0xED, 0xD5, 0xB5, 0x91, 0x6B, 0x46, 0x27, 0x10, 0x03, 0x01, 0x0A, 0x1E, 0x3B, 0x5D };

		/**
         * Sine wave samples for note G, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_G_4[] { 0x80, 0xC8, 0xF6, 0xFC, 0xD5, 0x91, 0x46, 0x10, 0x01, 0x1E, 0x5D };

		/**
         * Sine wave samples for note G, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_G_5[] { 0x80, 0xF6, 0xD5, 0x46, 0x01, 0x5D };

		/**
         * Sine wave samples for note G, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_G_6[] { 0x80, 0xD5, 0x01 };

		/**
         * Sine wave samples for note G, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_G_7[] { 0x80, 0x01 };

		/**
         * Sine wave samples for note G_Sharp, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_G_Sharp_3[] { 0x80, 0xA7, 0xCB, 0xE8, 0xF9, 0xFF, 0xF8, 0xE4, 0xC7, 0xA2, 0x7A, 0x52, 0x2F, 0x14, 0x04, 0x00, 0x09, 0x1E, 0x3D, 0x62 };

		/**
         * Sine wave samples for note G_Sharp, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_G_Sharp_4[] { 0x80, 0xCB, 0xF9, 0xF8, 0xC7, 0x7A, 0x2F, 0x04, 0x09, 0x3D };

		/**
         * Sine wave samples for note G_Sharp, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_G_Sharp_5[] { 0x80, 0xF9, 0xC7, 0x2F, 0x09 };

		/**
         * Sine wave samples for note G_Sharp, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_G_Sharp_6[] { 0x80, 0xC7, 0x09 };

		/**
         * Sine wave samples for note G_Sharp, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_G_Sharp_7[] { 0x80, 0x09 };

		/**
         * Sine wave samples for note A, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_A_3[] { 0x80, 0xAA, 0xCF, 0xEC, 0xFC, 0xFE, 0xF2, 0xD9, 0xB6, 0x8D, 0x62, 0x3B, 0x1B, 0x07, 0x00, 0x08, 0x1D, 0x3D, 0x65 };

		/**
         * Sine wave samples for note A, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_A_4[] { 0x80, 0xCF, 0xFC, 0xF2, 0xB6, 0x62, 0x1B, 0x00, 0x1D, 0x65 };

		/**
         * Sine wave samples for note A, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_A_5[] { 0x80, 0xFC, 0xB6, 0x1B, 0x1D };

		/**
         * Sine wave samples for note A, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_A_6[] { 0x80, 0xB6, 0x1D };

		/**
         * Sine wave samples for note A, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_A_7[] { 0x80, 0x1D };

		/**
         * Sine wave samples for note A_Sharp, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_A_Sharp_3[] { 0x80, 0xAC, 0xD3, 0xEF, 0xFE, 0xFC, 0xEB, 0xCC, 0xA3, 0x76, 0x4A, 0x25, 0x0B, 0x00, 0x05, 0x1A, 0x3B, 0x65 };

		/**
         * Sine wave samples for note A_Sharp, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_A_Sharp_4[] { 0x80, 0xD3, 0xFE, 0xEB, 0xA3, 0x4A, 0x0B, 0x05, 0x3B };

		/**
         * Sine wave samples for note A_Sharp, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_A_Sharp_5[] { 0x80, 0xFE, 0xA3, 0x0B, 0x3B };

		/**
         * Sine wave samples for note A_Sharp, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_A_Sharp_6[] { 0x80, 0xA3, 0x3B };

		/**
         * Sine wave samples for note A_Sharp, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_A_Sharp_7[] { 0x80, 0x3B };

		/**
         * Sine wave samples for note B, octave 3
         */
        constexpr uint8_t SINE_TABLE_DATA_B_3[] { 0x80, 0xAF, 0xD7, 0xF3, 0xFF, 0xF8, 0xE1, 0xBC, 0x8E, 0x5E, 0x33, 0x13, 0x02, 0x03, 0x16, 0x37, 0x63 };

		/**
         * Sine wave samples for note B, octave 4
         */
        constexpr uint8_t SINE_TABLE_DATA_B_4[] { 0x80, 0xD7, 0xFF, 0xE1, 0x8E, 0x33, 0x02, 0x16, 0x63 };

		/**
         * Sine wave samples for note B, octave 5
         */
        constexpr uint8_t SINE_TABLE_DATA_B_5[] { 0x80, 0xFF, 0x8E, 0x02, 0x63 };

		/**
         * Sine wave samples for note B, octave 6
         */
        constexpr uint8_t SINE_TABLE_DATA_B_6[] { 0x80, 0x8E, 0x63 };

		/**
         * Sine wave samples for note B, octave 7
         */
        constexpr uint8_t SINE_TABLE_DATA_B_7[] { 0x80, 0x63 };
    }

    /**
     * Number of samples processed per second for each sine wave table 
     */
    constexpr auto SAMPLE_RATE = 4096;

    /**
     * The minimum octave present in the table
     */
    constexpr size_t MIN_OCTAVE = 3;

    /**
     * The maximum octave present in the table
     */
    constexpr size_t MAX_OCTAVE = 7;
    
    /**
     * The maximum length of the tables
     */
    constexpr size_t MAX_LENGTH = 32;
    
    constexpr size_t ALL_SINE_TABLES_LENGTH_0 = 12;
    constexpr size_t ALL_SINE_TABLES_LENGTH_1 = 5;
    constexpr size_t ALL_SINE_TABLES_LENGTH = ALL_SINE_TABLES_LENGTH_0 * ALL_SINE_TABLES_LENGTH_1;
    
    /**
     * An empty sine table
     */
    constexpr auto SINE_TABLE_EMPTY = SineTable { .length = 0, .data = nullptr };

    /**
     * 2D array mapping musical note + octave to a table sampling its sine wave
     */
    constexpr SineTable ALL_SINE_TABLES[ALL_SINE_TABLES_LENGTH_0][ALL_SINE_TABLES_LENGTH_1]
	{
        { { .length = sizeof(data::SINE_TABLE_DATA_C_3), .data = data::SINE_TABLE_DATA_C_3 }, { .length = sizeof(data::SINE_TABLE_DATA_C_4), .data = data::SINE_TABLE_DATA_C_4 }, { .length = sizeof(data::SINE_TABLE_DATA_C_5), .data = data::SINE_TABLE_DATA_C_5 }, { .length = sizeof(data::SINE_TABLE_DATA_C_6), .data = data::SINE_TABLE_DATA_C_6 }, { .length = sizeof(data::SINE_TABLE_DATA_C_7), .data = data::SINE_TABLE_DATA_C_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_C_Sharp_3), .data = data::SINE_TABLE_DATA_C_Sharp_3 }, { .length = sizeof(data::SINE_TABLE_DATA_C_Sharp_4), .data = data::SINE_TABLE_DATA_C_Sharp_4 }, { .length = sizeof(data::SINE_TABLE_DATA_C_Sharp_5), .data = data::SINE_TABLE_DATA_C_Sharp_5 }, { .length = sizeof(data::SINE_TABLE_DATA_C_Sharp_6), .data = data::SINE_TABLE_DATA_C_Sharp_6 }, { .length = sizeof(data::SINE_TABLE_DATA_C_Sharp_7), .data = data::SINE_TABLE_DATA_C_Sharp_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_D_3), .data = data::SINE_TABLE_DATA_D_3 }, { .length = sizeof(data::SINE_TABLE_DATA_D_4), .data = data::SINE_TABLE_DATA_D_4 }, { .length = sizeof(data::SINE_TABLE_DATA_D_5), .data = data::SINE_TABLE_DATA_D_5 }, { .length = sizeof(data::SINE_TABLE_DATA_D_6), .data = data::SINE_TABLE_DATA_D_6 }, { .length = sizeof(data::SINE_TABLE_DATA_D_7), .data = data::SINE_TABLE_DATA_D_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_D_Sharp_3), .data = data::SINE_TABLE_DATA_D_Sharp_3 }, { .length = sizeof(data::SINE_TABLE_DATA_D_Sharp_4), .data = data::SINE_TABLE_DATA_D_Sharp_4 }, { .length = sizeof(data::SINE_TABLE_DATA_D_Sharp_5), .data = data::SINE_TABLE_DATA_D_Sharp_5 }, { .length = sizeof(data::SINE_TABLE_DATA_D_Sharp_6), .data = data::SINE_TABLE_DATA_D_Sharp_6 }, { .length = sizeof(data::SINE_TABLE_DATA_D_Sharp_7), .data = data::SINE_TABLE_DATA_D_Sharp_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_E_3), .data = data::SINE_TABLE_DATA_E_3 }, { .length = sizeof(data::SINE_TABLE_DATA_E_4), .data = data::SINE_TABLE_DATA_E_4 }, { .length = sizeof(data::SINE_TABLE_DATA_E_5), .data = data::SINE_TABLE_DATA_E_5 }, { .length = sizeof(data::SINE_TABLE_DATA_E_6), .data = data::SINE_TABLE_DATA_E_6 }, { .length = sizeof(data::SINE_TABLE_DATA_E_7), .data = data::SINE_TABLE_DATA_E_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_F_3), .data = data::SINE_TABLE_DATA_F_3 }, { .length = sizeof(data::SINE_TABLE_DATA_F_4), .data = data::SINE_TABLE_DATA_F_4 }, { .length = sizeof(data::SINE_TABLE_DATA_F_5), .data = data::SINE_TABLE_DATA_F_5 }, { .length = sizeof(data::SINE_TABLE_DATA_F_6), .data = data::SINE_TABLE_DATA_F_6 }, { .length = sizeof(data::SINE_TABLE_DATA_F_7), .data = data::SINE_TABLE_DATA_F_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_F_Sharp_3), .data = data::SINE_TABLE_DATA_F_Sharp_3 }, { .length = sizeof(data::SINE_TABLE_DATA_F_Sharp_4), .data = data::SINE_TABLE_DATA_F_Sharp_4 }, { .length = sizeof(data::SINE_TABLE_DATA_F_Sharp_5), .data = data::SINE_TABLE_DATA_F_Sharp_5 }, { .length = sizeof(data::SINE_TABLE_DATA_F_Sharp_6), .data = data::SINE_TABLE_DATA_F_Sharp_6 }, { .length = sizeof(data::SINE_TABLE_DATA_F_Sharp_7), .data = data::SINE_TABLE_DATA_F_Sharp_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_G_3), .data = data::SINE_TABLE_DATA_G_3 }, { .length = sizeof(data::SINE_TABLE_DATA_G_4), .data = data::SINE_TABLE_DATA_G_4 }, { .length = sizeof(data::SINE_TABLE_DATA_G_5), .data = data::SINE_TABLE_DATA_G_5 }, { .length = sizeof(data::SINE_TABLE_DATA_G_6), .data = data::SINE_TABLE_DATA_G_6 }, { .length = sizeof(data::SINE_TABLE_DATA_G_7), .data = data::SINE_TABLE_DATA_G_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_G_Sharp_3), .data = data::SINE_TABLE_DATA_G_Sharp_3 }, { .length = sizeof(data::SINE_TABLE_DATA_G_Sharp_4), .data = data::SINE_TABLE_DATA_G_Sharp_4 }, { .length = sizeof(data::SINE_TABLE_DATA_G_Sharp_5), .data = data::SINE_TABLE_DATA_G_Sharp_5 }, { .length = sizeof(data::SINE_TABLE_DATA_G_Sharp_6), .data = data::SINE_TABLE_DATA_G_Sharp_6 }, { .length = sizeof(data::SINE_TABLE_DATA_G_Sharp_7), .data = data::SINE_TABLE_DATA_G_Sharp_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_A_3), .data = data::SINE_TABLE_DATA_A_3 }, { .length = sizeof(data::SINE_TABLE_DATA_A_4), .data = data::SINE_TABLE_DATA_A_4 }, { .length = sizeof(data::SINE_TABLE_DATA_A_5), .data = data::SINE_TABLE_DATA_A_5 }, { .length = sizeof(data::SINE_TABLE_DATA_A_6), .data = data::SINE_TABLE_DATA_A_6 }, { .length = sizeof(data::SINE_TABLE_DATA_A_7), .data = data::SINE_TABLE_DATA_A_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_A_Sharp_3), .data = data::SINE_TABLE_DATA_A_Sharp_3 }, { .length = sizeof(data::SINE_TABLE_DATA_A_Sharp_4), .data = data::SINE_TABLE_DATA_A_Sharp_4 }, { .length = sizeof(data::SINE_TABLE_DATA_A_Sharp_5), .data = data::SINE_TABLE_DATA_A_Sharp_5 }, { .length = sizeof(data::SINE_TABLE_DATA_A_Sharp_6), .data = data::SINE_TABLE_DATA_A_Sharp_6 }, { .length = sizeof(data::SINE_TABLE_DATA_A_Sharp_7), .data = data::SINE_TABLE_DATA_A_Sharp_7 } },
		{ { .length = sizeof(data::SINE_TABLE_DATA_B_3), .data = data::SINE_TABLE_DATA_B_3 }, { .length = sizeof(data::SINE_TABLE_DATA_B_4), .data = data::SINE_TABLE_DATA_B_4 }, { .length = sizeof(data::SINE_TABLE_DATA_B_5), .data = data::SINE_TABLE_DATA_B_5 }, { .length = sizeof(data::SINE_TABLE_DATA_B_6), .data = data::SINE_TABLE_DATA_B_6 }, { .length = sizeof(data::SINE_TABLE_DATA_B_7), .data = data::SINE_TABLE_DATA_B_7 } }
	};
}

inline const char* get_note_name(const musical_note note, const bool prefer_flat = false)
{
    switch (note)
    {
        case musical_note::C: return musical_note_data::data::MUSICAL_NOTE_NAME_C;
		case musical_note::C_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_D_Flat : musical_note_data::data::MUSICAL_NOTE_NAME_C_Sharp;
		case musical_note::D: return musical_note_data::data::MUSICAL_NOTE_NAME_D;
		case musical_note::D_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_E_Flat : musical_note_data::data::MUSICAL_NOTE_NAME_D_Sharp;
		case musical_note::E: return musical_note_data::data::MUSICAL_NOTE_NAME_E;
		case musical_note::F: return musical_note_data::data::MUSICAL_NOTE_NAME_F;
		case musical_note::F_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_G_Flat : musical_note_data::data::MUSICAL_NOTE_NAME_F_Sharp;
		case musical_note::G: return musical_note_data::data::MUSICAL_NOTE_NAME_G;
		case musical_note::G_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_A_Flat : musical_note_data::data::MUSICAL_NOTE_NAME_G_Sharp;
		case musical_note::A: return musical_note_data::data::MUSICAL_NOTE_NAME_A;
		case musical_note::A_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_B_Flat : musical_note_data::data::MUSICAL_NOTE_NAME_A_Sharp;
		case musical_note::B: return musical_note_data::data::MUSICAL_NOTE_NAME_B;
        default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
    }
}

inline const char* get_note_name(const musical_note note, const uint8_t octave, const bool prefer_flat = false)
{
    switch (octave)
    {
        //Octave 3
		case 3:
            switch (note)
            {
                case musical_note::C: return musical_note_data::data::MUSICAL_NOTE_NAME_C_OCTAVE_3;
				case musical_note::C_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_D_Flat_OCTAVE_3 : musical_note_data::data::MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_3;
				case musical_note::D: return musical_note_data::data::MUSICAL_NOTE_NAME_D_OCTAVE_3;
				case musical_note::D_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_E_Flat_OCTAVE_3 : musical_note_data::data::MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_3;
				case musical_note::E: return musical_note_data::data::MUSICAL_NOTE_NAME_E_OCTAVE_3;
				case musical_note::F: return musical_note_data::data::MUSICAL_NOTE_NAME_F_OCTAVE_3;
				case musical_note::F_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_G_Flat_OCTAVE_3 : musical_note_data::data::MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_3;
				case musical_note::G: return musical_note_data::data::MUSICAL_NOTE_NAME_G_OCTAVE_3;
				case musical_note::G_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_A_Flat_OCTAVE_3 : musical_note_data::data::MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_3;
				case musical_note::A: return musical_note_data::data::MUSICAL_NOTE_NAME_A_OCTAVE_3;
				case musical_note::A_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_B_Flat_OCTAVE_3 : musical_note_data::data::MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_3;
				case musical_note::B: return musical_note_data::data::MUSICAL_NOTE_NAME_B_OCTAVE_3;
                default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
            }
		
		//Octave 4
		case 4:
            switch (note)
            {
                case musical_note::C: return musical_note_data::data::MUSICAL_NOTE_NAME_C_OCTAVE_4;
				case musical_note::C_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_D_Flat_OCTAVE_4 : musical_note_data::data::MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_4;
				case musical_note::D: return musical_note_data::data::MUSICAL_NOTE_NAME_D_OCTAVE_4;
				case musical_note::D_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_E_Flat_OCTAVE_4 : musical_note_data::data::MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_4;
				case musical_note::E: return musical_note_data::data::MUSICAL_NOTE_NAME_E_OCTAVE_4;
				case musical_note::F: return musical_note_data::data::MUSICAL_NOTE_NAME_F_OCTAVE_4;
				case musical_note::F_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_G_Flat_OCTAVE_4 : musical_note_data::data::MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_4;
				case musical_note::G: return musical_note_data::data::MUSICAL_NOTE_NAME_G_OCTAVE_4;
				case musical_note::G_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_A_Flat_OCTAVE_4 : musical_note_data::data::MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_4;
				case musical_note::A: return musical_note_data::data::MUSICAL_NOTE_NAME_A_OCTAVE_4;
				case musical_note::A_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_B_Flat_OCTAVE_4 : musical_note_data::data::MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_4;
				case musical_note::B: return musical_note_data::data::MUSICAL_NOTE_NAME_B_OCTAVE_4;
                default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
            }
		
		//Octave 5
		case 5:
            switch (note)
            {
                case musical_note::C: return musical_note_data::data::MUSICAL_NOTE_NAME_C_OCTAVE_5;
				case musical_note::C_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_D_Flat_OCTAVE_5 : musical_note_data::data::MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_5;
				case musical_note::D: return musical_note_data::data::MUSICAL_NOTE_NAME_D_OCTAVE_5;
				case musical_note::D_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_E_Flat_OCTAVE_5 : musical_note_data::data::MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_5;
				case musical_note::E: return musical_note_data::data::MUSICAL_NOTE_NAME_E_OCTAVE_5;
				case musical_note::F: return musical_note_data::data::MUSICAL_NOTE_NAME_F_OCTAVE_5;
				case musical_note::F_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_G_Flat_OCTAVE_5 : musical_note_data::data::MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_5;
				case musical_note::G: return musical_note_data::data::MUSICAL_NOTE_NAME_G_OCTAVE_5;
				case musical_note::G_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_A_Flat_OCTAVE_5 : musical_note_data::data::MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_5;
				case musical_note::A: return musical_note_data::data::MUSICAL_NOTE_NAME_A_OCTAVE_5;
				case musical_note::A_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_B_Flat_OCTAVE_5 : musical_note_data::data::MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_5;
				case musical_note::B: return musical_note_data::data::MUSICAL_NOTE_NAME_B_OCTAVE_5;
                default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
            }
		
		//Octave 6
		case 6:
            switch (note)
            {
                case musical_note::C: return musical_note_data::data::MUSICAL_NOTE_NAME_C_OCTAVE_6;
				case musical_note::C_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_D_Flat_OCTAVE_6 : musical_note_data::data::MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_6;
				case musical_note::D: return musical_note_data::data::MUSICAL_NOTE_NAME_D_OCTAVE_6;
				case musical_note::D_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_E_Flat_OCTAVE_6 : musical_note_data::data::MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_6;
				case musical_note::E: return musical_note_data::data::MUSICAL_NOTE_NAME_E_OCTAVE_6;
				case musical_note::F: return musical_note_data::data::MUSICAL_NOTE_NAME_F_OCTAVE_6;
				case musical_note::F_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_G_Flat_OCTAVE_6 : musical_note_data::data::MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_6;
				case musical_note::G: return musical_note_data::data::MUSICAL_NOTE_NAME_G_OCTAVE_6;
				case musical_note::G_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_A_Flat_OCTAVE_6 : musical_note_data::data::MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_6;
				case musical_note::A: return musical_note_data::data::MUSICAL_NOTE_NAME_A_OCTAVE_6;
				case musical_note::A_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_B_Flat_OCTAVE_6 : musical_note_data::data::MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_6;
				case musical_note::B: return musical_note_data::data::MUSICAL_NOTE_NAME_B_OCTAVE_6;
                default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
            }
		
		//Octave 7
		case 7:
            switch (note)
            {
                case musical_note::C: return musical_note_data::data::MUSICAL_NOTE_NAME_C_OCTAVE_7;
				case musical_note::C_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_D_Flat_OCTAVE_7 : musical_note_data::data::MUSICAL_NOTE_NAME_C_Sharp_OCTAVE_7;
				case musical_note::D: return musical_note_data::data::MUSICAL_NOTE_NAME_D_OCTAVE_7;
				case musical_note::D_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_E_Flat_OCTAVE_7 : musical_note_data::data::MUSICAL_NOTE_NAME_D_Sharp_OCTAVE_7;
				case musical_note::E: return musical_note_data::data::MUSICAL_NOTE_NAME_E_OCTAVE_7;
				case musical_note::F: return musical_note_data::data::MUSICAL_NOTE_NAME_F_OCTAVE_7;
				case musical_note::F_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_G_Flat_OCTAVE_7 : musical_note_data::data::MUSICAL_NOTE_NAME_F_Sharp_OCTAVE_7;
				case musical_note::G: return musical_note_data::data::MUSICAL_NOTE_NAME_G_OCTAVE_7;
				case musical_note::G_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_A_Flat_OCTAVE_7 : musical_note_data::data::MUSICAL_NOTE_NAME_G_Sharp_OCTAVE_7;
				case musical_note::A: return musical_note_data::data::MUSICAL_NOTE_NAME_A_OCTAVE_7;
				case musical_note::A_Sharp: return prefer_flat? musical_note_data::data::MUSICAL_NOTE_NAME_B_Flat_OCTAVE_7 : musical_note_data::data::MUSICAL_NOTE_NAME_A_Sharp_OCTAVE_7;
				case musical_note::B: return musical_note_data::data::MUSICAL_NOTE_NAME_B_OCTAVE_7;
                default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
            }
        default: return musical_note_data::data::MUSICAL_NOTE_NAME_NONE;
    }
}

#endif //AUDIO_CONTROLLER_MUSICAL_NOTE_DATA_H