const NOW = new Date();
const FREQUENCY_C0 = 16.35;
const SAMPLE_RATE = 1 << 17;
const OCTAVES = [0, 7];
const NOTE_SYMBOLS = [
    ['C'],
    ['C_Sharp', 'D_Flat'],
    ['D'],
    ['D_Sharp', 'E_Flat'],
    ['E'],
    ['F'],
    ['F_Sharp', 'G_Flat'],
    ['G'],
    ['G_Sharp', 'A_Flat'],
    ['A'],
    ['A_Sharp', 'B_Flat'],
    ['B']
];

function ParseArgs(argv) {
    let dictionary = {};

    for(let i = 2; i < argv.length; i++) {
        let arg = argv[i];

        if(arg.startsWith('--')) {
            arg = arg.substring(2);

            if(arg == '')
                continue;

            if(i + 1 < argv.length) {
                let value = argv[i + 1];

                if(!value.startsWith('-')) {
                    dictionary[arg] = value;
                    i++;
                }
            }
        }
    }

    return dictionary;
}

/**
 * Get the frequency of the given note + octave
 * @param {number} note Ordinal into NOTE_SYMBOLS
 * @param {number} octave Octave to calculate frequency for
 * @returns {number}
 */
function musical_note_freq_hz(note, octave)
{
    return FREQUENCY_C0 * Math.pow(2, (note + (octave * NOTE_SYMBOLS.length)) / (NOTE_SYMBOLS.length * 1.0));
}

/**
 * Map the given value between 0 and 1 to a byte from 0 to 255
 * @param {number} value [0-1]
 * @returns {number} [0-255]
 */
function map_to_byte(value) {
    if(value < 0 || value >= 1)
        return 255;

    return Math.round(255 * value);
}

/**
 * @param {number} note Ordinal into NOTE_SYMBOLS
 * @param {number} octave Octave to calculate frequency for
 * @returns An array of values from [0, 255], each representing a single sample of
 * sound intensity, at SAMPLE_RATE hz. Length of array is for one period (rounded up).
 */
function generate_table(note, octave) {
    const frequency = musical_note_freq_hz(note, octave);
    const period = 1.0 / frequency;
    const samples_per_period = SAMPLE_RATE * period;
    const samples_per_period_ceiling = Math.ceil(samples_per_period);

    let table = [];

    for(let i = 0; i < samples_per_period_ceiling; i++) {
        let t = i * SAMPLE_RATE;

        //Calculate sine wave value at t, translating and scaling to lie
        //between [0, 1]
        const value = (1 + Math.sin(2 * Math.PI * t * frequency)) / 2;

        table.push(map_to_byte(value));
    }

    return table;
}

const args = ParseArgs(process.argv);

//Generate table for all specified notes/octaves
let note_tables = [];

for(let i = 0; i < NOTE_SYMBOLS.length; i++) {
    let octave_tables = [];

    for(let j = OCTAVES[0]; j <= OCTAVES[1]; j++) {
        octave_tables.push(generate_table(i, j));
    }

    note_tables.push(octave_tables);
}

const file_content = `
//
// File generated by script '${__filename}' on ${(NOW.getMonth() + 1).toString().padStart(2, '0')}/${NOW.getDate().toString().padStart(2, '0')}/${NOW.getFullYear().toString().padStart(4, '0')} at ${NOW.getHours().toString().padStart(2, '0')}:${NOW.getMinutes().toString().padStart(2, '0')}.
// Contains samples of sine waves, mapped from [0, 1] => [0, 255], at a sample rate of ${SAMPLE_RATE} Hz.
//

#ifndef AUDIO_CONTROLLER_MUSICAL_NOTE_DATA_H
#define AUDIO_CONTROLLER_MUSICAL_NOTE_DATA_H
#include "sine_table.h"

namespace sine_tables {
    namespace data {   
        ${note_tables.map((note_table, note_ndx) => {
            const names = NOTE_SYMBOLS[note_ndx];
            const primary_name = names[0];

            return note_table.map((table, octave) => {
                return `
        /**
         * Sine wave samples for note ${primary_name}, octave ${octave}
         */
        constexpr uint8_t SINE_TABLE_DATA_${primary_name}_${octave}[] { ${table.map(value => `0x${value.toString(16).toUpperCase().padStart(2, '0')}`).reduce((a, b) => `${a}, ${b}`)} };
                `.trim();
            }).reduce((a, b) => `${a}\r\n\r\n\t\t${b}`);
        }).reduce((a, b) => `${a}\r\n\r\n\t\t${b}`)}
    }

    /**
     * Number of samples processed per second for each sine wave table 
     */
    constexpr auto SAMPLE_RATE = ${SAMPLE_RATE};

    constexpr size_t ALL_SINE_TABLES_LENGTH_0 = ${NOTE_SYMBOLS.length};
    constexpr size_t ALL_SINE_TABLES_LENGTH_1 = ${1 + OCTAVES[1] - OCTAVES[0]};

    /**
     * 2D array mapping musical note + octave to a table sampling its sine wave
     */
    constexpr SineTable ALL_SINE_TABLES[ALL_SINE_TABLES_LENGTH_0][ALL_SINE_TABLES_LENGTH_1]
	{
        ${note_tables.map((note_table, note_ndx) => {
            const names = NOTE_SYMBOLS[note_ndx];
            const primary_name = names[0];

            return `
                { ${note_table.map((_, octave) => {
                    return `{ .length = sizeof(data::SINE_TABLE_DATA_${primary_name}_${octave}), .data = data::SINE_TABLE_DATA_${primary_name}_${octave} }`;
                }).reduce((a, b) => `${a}, ${b}`)} }
            `.trim();
        }).reduce((a, b) => `${a},\r\n\t\t${b}`)}
	};
}

#endif //AUDIO_CONTROLLER_MUSICAL_NOTE_DATA_H
`.trim();

console.log(file_content);

if(!args.output)
    throw new Error(`Output file (--output) is required.`);

console.log(`Saving file to ${args.output}`);

require('fs').writeFileSync(args.output, file_content);